### ISSUE TITLE
XOR should be true (XOR_2)

### ISSUE THREAD

**Issue by emilwallner** [emilwallner/Expert-System#10]
B + C => A

D ^ E => B

B => C

=D

A: False

?A

**Comment by simdax** [comment]
Why A should be true ?

D ^E => B / D is True et E is False
True ^ False => False so for rule 2 B is False
B + C => A  , B is false, so A is False

**Comment by emilwallner** [comment]
True ^ False => True

![download](https://user-images.githubusercontent.com/12543699/59419158-9b4dfb00-8dca-11e9-82ce-6ce0d14a7bd2.png)

**Comment by simdax** [comment]
Yes of course!

Le jeu. 13 juin 2019 à 11:02, Emil Wallner <notifications@github.com> a
écrit :
