### ISSUE TITLE
Parentheses wrong logic

### ISSUE THREAD

**Issue by emilwallner** [emilwallner/Expert-System#5]
A | B + C => E

(F | G) + H => E

=FH

E: False

----

E should be True

**Comment by emilwallner** [comment]
A | B + C => E

(F | G) + H => E



=GH



E: False

?E

-----


E should be True

**Comment by emilwallner** [comment]
A | B + C => E

(F | G) + H => E



=A



E: True

?E

----
Should be false

**Comment by simdax** [comment]
Could you put the ref of the tests ?
I think I've put a fix, try and close them if it is :)
